### ISSUE TITLE
proposal: Invalid redirection from trpc.group

### ISSUE THREAD

**Issue by Andrew-M-C** [trpc-ecosystem/go-naming-polarismesh#13]
When requesting URL [https://trpc.group/trpc-go/trpc-naming-polarismesh](https://trpc.group/trpc-go/trpc-naming-polarismesh), browser should be redirected to `https://github.com/trpc-ecosystem/go-naming-polarismesh`. However `https://github.com/trpc-ecosystem/trpc-go-naming-polarismesh` is returned, which showing 404.

**Comment by tocrafty** [comment]
@Leoyoungxh Please add a special rule for polarishmesh in `trpc.group` redirect server.

**Comment by Leoyoungxh** [comment]
@tocrafty @Andrew-M-C 
Sure, it's fixed now. Please give it another try.

**Comment by Andrew-M-C** [comment]
Fast as Lightning! 👍
